config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :locations
  resources :departments
  resources :titles

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'

  delete "/logout", to: "sessions#destroy", as: "logout"
  resources :users, only: [:new, :create]

  root 'welcome#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :subordinates, class_name: "Employee",foreign_key: "manager_id"
  belongs_to :title
  belongs_to :department
  belongs_to :location
  belongs_to :manager, class_name: "Employee", optional: true

  has_attached_file :photo, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/models/location.rb
class Location < ApplicationRecord
    has_many :employees
end

app/models/title.rb
class Title < ApplicationRecord
    has_many :employees
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def current_user
      # byebug
      @user = (User.find_by(id: session[:user_id]) || User.new)
      # byebug
    end
  
    def logged_in?
      # byebug
      current_user.id != nil
    end
  
    def require_logged_in
      # byebug
      return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end
  
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    def index
        @departments = Department.all
    end

    def show
        @department = get_department
    end
    
    private

    def get_department
        Department.find(params[:id])
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        emps = Employee.all
        @employees = emps.sort_by(&:name)
    end
    def show
        @employee = get_employee
    end

    def new
        @employee = Employee.new
    end
    def create
        # byebug
        employee = Employee.create(employee_params)
        # byebug
        redirect_to employees_path
    end

    def edit
        @employee = get_employee
    end
    def update
        employee = get_employee
        employee.update(employee_params)
        # byebug
        redirect_to employee_path
    end

    def destroy
        employee = get_employee
        employee.destroy
        redirect_to employees_path
    end

    private

    def get_employee
        Employee.find(params[:id])
    end

    def employee_params
        # byebug
        params.require(:employee).permit(:name, :photo, :title_id, :department_id, :location_id, :manager_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
        @locations = Location.all
    end

    def show
        @location = get_location
    end
    
    private

    def get_location
        Location.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
    end
  
    def create
        # byebug
      user = User.find_by(name: params[:user][:name])
  
      user = user.try(:authenticate, params[:user][:password])
  
      return redirect_to(controller: 'sessions', action: 'new') unless user
  
      session[:user_id] = user.id
  
      @user = user
  
    #   redirect_to controller: 'welcome', action: 'home'
      redirect_to controller: 'employees', action: 'index'
    end
  
    def destroyx
      byebug
      session.delete :user_id
        redirect_to '/'
    end
    def destroy
      session.delete(:user_id)
      # response
      redirect_to login_path
    end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
    def index
        @titles = Title.all 
    end
    def show
        @title = Title.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      return redirect_to controller: 'users', action: 'new' unless @user.save
      session[:user_id] = @user.id
      redirect_to controller: 'welcome', action: 'home'
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :require_logged_in
  
    def home
      redirect_to employees_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/departments/index.html.erb
<h1>All Departments</h1>

<%@departments.each do |dept|%>
    <%=link_to dept.name, dept%><br>
<%end%>

app/views/departments/show.html.erb
<h1>Department: <%=@department.name%>:</h1>
<div class='pageAll'>
    <ul>
        <%@department.employees.each do |emp|%>
            <li><%=link_to emp.name, emp%>, <%=emp.title.name%> in <%=emp.department.name%> department</li>
            <br>
        <%end%>
    </ul>   
</div>

app/views/employees/edit.html.erb
<h1>Updating Employee</h1>

<div class='pageAll'>

<div class='formAll'>
<%=form_for @employee do |f|%>
    <br>
    <%=f.label :name%>
    <%=f.text_field :name%>
    <%= f.label :title_id %>
    <%=f.collection_select :title_id, Title.all, :id, :name%>
    <%= f.label :department_id %>
    <%=f.collection_select :department_id, Department.order(:name), :id, :name%>
    <br><br>
    <%= f.label :location_id %>
    <%=f.collection_select :location_id, Location.all, :id, :site%>
    <%= f.label :manager_id %>
    <%=f.collection_select :manager_id, Employee.order(:name), :id, :name%>
    <%= f.file_field :photo %>

    <%=f.submit%>
<%end%>
</div>
</div>

app/views/employees/index.html.erb
    <div class='inner'><%= button_to 'Create New Employee', new_employee_path, :method => :get %></div>
    <div class='inner'><%= button_to 'Log out', logout_path, :method => :delete %></div>


    <h1>All Employees</h1>
<div class='pageAll'>
    <div class='formAll'>
        <br>
        <%@employees.each do |employee|%>
            <%=link_to employee.name, employee%><br>
        <%end%>
    </div>
    <br><br>
</div>

     

app/views/employees/new.html.erb
<h1>Creating New Employee</h1>
<div class='pageAll'>
<div class='formAll'>
<%=form_for @employee do |f|%>
    <br>
    <%=f.label :name%>
    <%=f.text_field :name%>
    <%= f.label :title_id %>
    <%=f.collection_select :title_id, Title.all, :id, :name%>
    <%= f.label :department_id %>
    <%=f.collection_select :department_id, Department.order(:name), :id, :name%>
    <br><br>
    <%= f.label :location_id %>
    <%=f.collection_select :location_id, Location.all, :id, :site%>
    <%= f.label :manager_id %>
    <%=f.collection_select :manager_id, Employee.order(:name), :id, :name%>
    <%= f.file_field :photo %>

    <%=f.submit%>
<%end%>
</div>
</div>

app/views/employees/show.html.erb
<div class="inner"><%= button_to 'Main', employees_path, :method => :get %></div>
<div class="inner"><%= button_to 'Edit', edit_employee_path, :method => :get %></div>
<div class="inner"><%= button_to "delete", nil, :method => :delete %></div>

<h1><%=@employee.name%></h1>

<div class='pageAll'>
    
    <div class='formAll'>
        ----------------------------------------------------------------------------------     
        <h4><%=@employee.title.name%>,  <%=link_to @employee.department.name, department_path(@employee.department_id)%></h4>
        
        Location : <%=link_to @employee.location.site, location_path(@employee.location_id)%>
        <br><br>
        Manager :
        <%if !!@employee.manager == true%>
            <%=link_to @employee.manager.name, @employee.manager%><br>
        <%end%>
        <br><br>

        <strong>My Subordinates:</strong>
        <ul class=subordinatce_box>

            <%@employee.subordinates.each do |emp|%>
                <br>
                <li><%=link_to emp.name, emp%>, <%=emp.title.name%> in <%=emp.department.name%></li>
                
                <%if !emp.subordinates.empty?%>
                    <div class='sub_lst'><ul>
                    <%emp.subordinates.each do |sub|%>
                        <li><%=sub.name%></li>
                    <%end%>
                    </ul></div>
                <%end%>
            <%end%>
        </ul>
    </div>

    <div class='img'>
        <%= image_tag @employee.photo.url(:medium) %><br>
    </div>
</div>

app/views/locations/index.html.erb
<h1>All Locations</h1>

<%@locations.each do |loc|%>
    <%=link_to loc.site, loc%><br>
<%end%>

app/views/locations/show.html.erb
<h1>Employees in <%=@location.site%>:</h1>
<div class='pageAll'>
    <ul>
        <%@location.employees.each do |emp|%>
            <li><%=link_to emp.name, emp%>, <%=emp.title.name%> in <%=emp.department.name%> department</li>
            <br>
        <%end%>
    </ul>
</div>

app/views/titles/index.html.erb
<h1>All Titles</h1>
<%@titles.each do |t|%>
    <%=link_to t.name, t%><br>
<%end%>

app/views/titles/show.html.erb
<%=@title.name%>

app/views/users/home.html.erb
<h1>Hi there, <%= current_user.name %></h1>.
<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>
<div class='pageAll'>
<br>
  <div class=XformAll1d>
  <br>
    <%= form_for @user, controller: 'users', action: 'create' do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "create" %>
    <% end %>
  </div>
</div>

app/views/welcome/home.html.erb
<h1>Hi, <%= @user.name %></h1>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>

  <input type=submit value='logout'>
<% end %>